// 🔥 Auto-generated Live Components Registration
// This file is automatically generated during build time - DO NOT EDIT MANUALLY
// Generated at: 2026-03-16T00:48:47.361Z

import { LiveAdminPanel } from "../../app/server/live/LiveAdminPanel"
import { LiveCounter } from "../../app/server/live/LiveCounter"
import { LiveForm } from "../../app/server/live/LiveForm"
import { LiveLocalCounter } from "../../app/server/live/LiveLocalCounter"
import { LivePingPong } from "../../app/server/live/LivePingPong"
import { LiveProtectedChat } from "../../app/server/live/LiveProtectedChat"
import { LiveRoomChat } from "../../app/server/live/LiveRoomChat"
import { LiveSharedCounter } from "../../app/server/live/LiveSharedCounter"
import { LiveUpload } from "../../app/server/live/LiveUpload"
import { componentRegistry } from "../server/live"

// Register all components statically for production bundle
function registerAllComponents() {
  try {
    // Auto-generated component registrations
    componentRegistry.registerComponentClass('LiveAdminPanel', LiveAdminPanel)
    componentRegistry.registerComponentClass('LiveCounter', LiveCounter)
    componentRegistry.registerComponentClass('LiveForm', LiveForm)
    componentRegistry.registerComponentClass('LiveLocalCounter', LiveLocalCounter)
    componentRegistry.registerComponentClass('LivePingPong', LivePingPong)
    componentRegistry.registerComponentClass('LiveProtectedChat', LiveProtectedChat)
    componentRegistry.registerComponentClass('LiveRoomChat', LiveRoomChat)
    componentRegistry.registerComponentClass('LiveSharedCounter', LiveSharedCounter)
    componentRegistry.registerComponentClass('LiveUpload', LiveUpload)
    
    console.log('📝 Live components registered successfully! (9 components)')
  } catch (error) {
    console.warn('⚠️ Error registering components:', error)
  }
}

// Auto-register components
registerAllComponents()

// Export all components to ensure they're included in the bundle
export { 
  LiveAdminPanel,
  LiveCounter,
  LiveForm,
  LiveLocalCounter,
  LivePingPong,
  LiveProtectedChat,
  LiveRoomChat,
  LiveSharedCounter,
  LiveUpload
}
