// Auto-generated Live Components Registration
// Generated by @fluxstack/live — DO NOT EDIT MANUALLY
// Generated at: 2026-03-25T22:30:53.343Z

import { ProDashboard } from "./ProDashboard"
import { ProtectedNotes } from "./ProtectedNotes"
import { PublicCounter } from "./PublicCounter"

// Component classes array for LiveServer({ components }) option
export const liveComponentClasses = [
  ProDashboard,
  ProtectedNotes,
  PublicCounter,
]
