// @fluxstack/live-client - Binary State Codec (Client-side decoder)
//
// Decodes binary state deltas generated by the server's BinaryStateCodec.
// Browser-safe: only uses TextDecoder, DataView, Uint8Array.
//
// Supports two modes:
//   1. Auto-infer: created from initialState (types inferred via typeof)
//   2. Explicit schema: field→type map for optimized wire sizes

const _dec = new TextDecoder()

const TYPE_UINT8    = 0
const TYPE_UINT16   = 1
const TYPE_UINT32   = 2
const TYPE_INT8     = 3
const TYPE_INT16    = 4
const TYPE_INT32    = 5
const TYPE_FLOAT32  = 6
const TYPE_FLOAT64  = 7
const TYPE_BOOLEAN  = 8
const TYPE_STRING   = 9

type WireType = typeof TYPE_UINT8 | typeof TYPE_UINT16 | typeof TYPE_UINT32 |
  typeof TYPE_INT8 | typeof TYPE_INT16 | typeof TYPE_INT32 |
  typeof TYPE_FLOAT32 | typeof TYPE_FLOAT64 | typeof TYPE_BOOLEAN | typeof TYPE_STRING

export type BinaryFieldType =
  'uint8' | 'uint16' | 'uint32' |
  'int8' | 'int16' | 'int32' |
  'float32' | 'float64' |
  'boolean' | 'string'

const TYPE_NAME_MAP: Record<BinaryFieldType, WireType> = {
  uint8: TYPE_UINT8, uint16: TYPE_UINT16, uint32: TYPE_UINT32,
  int8: TYPE_INT8, int16: TYPE_INT16, int32: TYPE_INT32,
  float32: TYPE_FLOAT32, float64: TYPE_FLOAT64,
  boolean: TYPE_BOOLEAN, string: TYPE_STRING,
}

interface FieldDef {
  name: string
  wireType: WireType
}

/**
 * Client-side binary state codec.
 *
 * @example Auto-infer from initialState
 * ```ts
 * const codec = new BinaryStateCodec({ count: 0, name: '', active: false })
 * ```
 *
 * @example Explicit schema (must match server)
 * ```ts
 * const codec = new BinaryStateCodec(
 *   { x: 0, y: 0, hp: 100, name: '' },
 *   { x: 'float32', y: 'float32', hp: 'uint8', name: 'string' }
 * )
 * ```
 */
export class BinaryStateCodec<TState = Record<string, any>> {
  private readonly _fields: FieldDef[]
  private readonly _bitmaskBytes: number

  constructor(defaultState: TState, schema?: Record<string, BinaryFieldType>) {
    this._fields = []
    const state = defaultState as Record<string, any>

    for (const key of Object.keys(state)) {
      if (schema && key in schema) {
        this._fields.push({ name: key, wireType: TYPE_NAME_MAP[schema[key]] })
        continue
      }

      const t = typeof state[key]
      if (t === 'number') {
        this._fields.push({ name: key, wireType: TYPE_FLOAT64 })
      } else if (t === 'boolean') {
        this._fields.push({ name: key, wireType: TYPE_BOOLEAN })
      } else if (t === 'string') {
        this._fields.push({ name: key, wireType: TYPE_STRING })
      }
      // Arrays, objects, null → skipped (server sends via JSON fallback)
    }

    this._bitmaskBytes = Math.ceil(this._fields.length / 8) || 1
  }

  decodeDelta(buf: Uint8Array): Partial<TState> {
    const view = new DataView(buf.buffer, buf.byteOffset, buf.byteLength)
    const result: Record<string, any> = {}
    let offset = this._bitmaskBytes

    for (let i = 0; i < this._fields.length; i++) {
      if (!(buf[i >> 3] & (1 << (i & 7)))) continue
      const field = this._fields[i]

      switch (field.wireType) {
        case TYPE_UINT8:
          result[field.name] = buf[offset]; offset += 1; break
        case TYPE_UINT16:
          result[field.name] = view.getUint16(offset, true); offset += 2; break
        case TYPE_UINT32:
          result[field.name] = view.getUint32(offset, true); offset += 4; break
        case TYPE_INT8:
          result[field.name] = view.getInt8(offset); offset += 1; break
        case TYPE_INT16:
          result[field.name] = view.getInt16(offset, true); offset += 2; break
        case TYPE_INT32:
          result[field.name] = view.getInt32(offset, true); offset += 4; break
        case TYPE_FLOAT32:
          result[field.name] = view.getFloat32(offset, true); offset += 4; break
        case TYPE_FLOAT64:
          result[field.name] = view.getFloat64(offset, true); offset += 8; break
        case TYPE_BOOLEAN:
          result[field.name] = buf[offset] === 1; offset += 1; break
        case TYPE_STRING: {
          const len = view.getUint16(offset, true); offset += 2
          result[field.name] = _dec.decode(buf.subarray(offset, offset + len)); offset += len
          break
        }
      }
    }

    return result as Partial<TState>
  }
}
