import { defineConfig } from 'tsup'

export default defineConfig({
  entry: {
    'index': 'src/index.ts',
    'framework/index': 'src/framework/index.ts',
    'plugins/index': 'src/plugins/index.ts',
    'server/index': 'src/server/index.ts',
    'client/index': 'src/client/index.ts',
    'build/index': 'src/build/index.ts',
    'cli/index': 'src/cli/index.ts',
    'utils/index': 'src/utils/index.ts',
    'types/index': 'src/types/index.ts',
    'testing/index': 'src/testing/index.ts',
    'config/index': 'src/config/index.ts',
  },
  format: ['esm'],
  dts: true,
  sourcemap: true,
  clean: true,
  target: 'es2022',
  splitting: false,
  treeshake: true,
  external: [
    'elysia',
    'vite',
    'bun',
    '@elysiajs/swagger',
    '@elysiajs/eden',
    '@vitejs/plugin-react',
    '@fluxstack/live',
    '@fluxstack/live-elysia',
    '@fluxstack/live-react',
    '@fluxstack/live-client',
    '@server/live/LiveUpload',
    'react',
    'react-dom',
    'zustand',
  ],
})
